version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-with-docker
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Jenkins数据持久化
      - jenkins_home:/var/jenkins_home
      # Docker socket挂载
      - /var/run/docker.sock:/var/run/docker.sock
      # 时区配置
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xmx2048m
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge
