cluster.name: regulation-cluster
node.name: regulation-node
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
bootstrap.memory_lock: false
xpack.security.enabled: false
# 中文分词插件配置（如果安装了IK分词器）

